site_name: Digital Porous Media Portal Documentation
site_description: Documentation for Digital Porous Media Portal
site_author: Digital Porous Media Portal Team
site_url: https://digitalporousmedia.org
repo_url: https://github.com/digital-porous-media/dpm_docs
edit_uri: edit/main/docs/

theme:
  name: tacc_readthedocs
  # "ReadTheDocs" Theme Features
  logo: https://cdn.jsdelivr.net/gh/TACC/Core-CMS-Custom@621b441/digitalrocks_assets/logo/logo--black.svg
  # "TACC" Theme Features
  portal_url: https://digitalporousmedia.org
  portal_name: digitalporousmedia.org

extra_css:
  - css/extra.css

markdown_extensions:
  - extra
  - admonition
  - toc:
      permalink: "" # i.e. `true` but without "¶"
      permalink_class: headerlink fa fa-link
      permalink_title: Link to Heading
  # PyMdown Extensions
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.saneheaders

# add contents from agu presentations
nav:
  - Digital Porous Media Essentials:
    - Documentation Overview: index.md
    #- About Us: about_us.md
    - How to Cite: cite.md
    #- User Agreement: user_agreement.md
  - Applications:
    - Community Data: community_data.md
    - Jupyter Notebooks: jupyter_docs.md
    - Digital Porous Media Tools (DPM Tools): https://github.com/digital-porous-media/dpm_tools
  - Data:
    - Download Data: download_data.md
    - Upload and Curate Data: upload_data.md
    - Manage Data: manage_data.md
  - Engage:
    - LinkedIn: https://www.linkedin.com/company/digital-porous-media/
  - Learn:
    - Upcoming Tutorials: new_tutorials.md
    - Past Tutorials: past_tutorials.md
  - Policies:
    - User Agreement: user_agreement.md
  - Admin:
    - Onboarding Admin: onboarding_admin.md

plugins:
  - search
